program: train.py
method: random
entity: 'sandracl72'
project: 'nuscenes_pgp'
metric:
  goal: minimize
  name: val/min_ade_5
early_terminate:
  type: hyperband
  min_iter: 6
parameters: 
  seed:
    min: 0
    max: 10000000
  aggregator_args.num_heads:
    values: [32 ]
  aggregator_args.pre_train:
    values: [ False]
  encoder_args.target_agent_enc_size:
     values: [32] #[32,64,128]
  encoder_args.target_agent_emb_size:
    values: [16] #[16,32] 
  encoder_args.num_heads_lanes:
    values: [1] #[1,2,4]
  encoder_args.feat_drop:
    #max: 0.4 
    #min: 0.
    values: [0.0]   
  encoder_args.attn_drop:
    #max: 0.4 
    #min: 0.
    values: [0.0]
  encoder_args.residual:
    values: [False]
  encoder_args.num_layers:
    values: [2]  
    # max: 4
    # min: 1  
  encoder_args.node_attn_size:
    values: [32] #[32,64,128]
  encoder_args.hg:
    values: ["hgcn"]
  optim_args.scheduler_step:
    values: [10] #,20,50]
  optim_args.lr:
    values: [0.001] #,0.0001, 0.00005]
  batch_size:
    values : [64] #[16,32,64,128]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "-c"
  - "/home/sandra/PROGRAMAS/PGP/configs/pgp_scout_gatx2_lvm_traversal.yml"
  - "--sweep"
  - "-d"
  - "/media/14TBDISK/sandra/nuscenes_processed/preprocessed_pgp/data-hetero"
  - "-o"
  - "/media/14TBDISK/sandra/PGP/pgp-scout/"
  - "-n"
  - "100"
  - "-r"
  - "/media/14TBDISK/nuscenes/"
  - ${args}